<?php

define('DOG__ENV', 'dev');
define('DOG__OPTION_PREFIX', 'dog__');
define('DOG__PLUGIN_PREFIX', 'dog-');
define('DOG__TEXT_DOMAIN', 'dog');
define('DOG__THEMES', 'dog, dogx');
define('DOG__NC_NAME', 'non4c0ef5ece8c4765116c845babxg7y');
define('DOG__NC_VAR_PREFIX', 'nc__');
define('DOG__HONEYPOT_ENABLED', true);
define('DOG__STATIC_ASSETS_URL', null);
define('DOG__STATIC_BASE_ASSETS_URL', null);
define('DOG__HP_TIMER_NAME', 'hon6c0ef5ece8c4765116c845babxgxx');
define('DOG__HP_JAR_NAME', 'dat4c0ef5ece8c4765116c845babcea6');
define('DOG__HP_TIMER_SECONDS', 1);
define('DOG__TIMEZONE', 'Europe/Bucharest');
define('DOG__ENTRY_CSS_CLASS_META_KEY', 'dog_entry_css_class');
define('DOG__SESSION_KEY_FLASH', 'flash');
define('DOG__SESSION_KEY_SUCCESS', 'success');
define('DOG__SESSION_KEY_ERROR', 'error');
define('DOG__THEME_NAME', 'dogx');
define('DOG__BASE_THEME_NAME', 'dog');
define('DOG__PREFIX', 'dog__');
define('DOG__PREFIX_ADMIN', 'dog_admin__');
define('DOG__PREFIX_X', 'dogx__');
define('DOG__COMPRESSED_ASSET_DIR', '_min');
define('DOG__SHORTCODE_KEYWORD_CONTENT', '*content*');
define('DOG__SHORTCODE_COMMENT_REGEX', '\s*~~(.*?)~~');
define('DOG__AJAX_RESPONSE_STATUS_SUCCESS', md5('ajaxresponseok'));
define('DOG__AJAX_RESPONSE_STATUS_ERROR', md5('ajaxresponseerror'));
define('DOG__TRANSIENT_FLASH_MESSAGES', 'dog__flash_messages');
define('DOG__TRANSIENT_FLASH_KEY_SUCCESS', 'success');
define('DOG__TRANSIENT_FLASH_KEY_ERROR', 'error');
define('DOG__TRANSIENT_FLASH_KEY_WARNING', 'warning');
define('DOG__TRANSIENT_FLASH_EXPIRE', 60 * 5);
define('DOG_ADMIN__TRANSIENT_FORM_RESPONSE', 'dog__form_response');